name: test

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  python:
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: zacharyburnett/setup-abseil-cpp@41fabae9b8c6a76c1b9612c8611c50b498bbeda1 # 1.0.3
        with:
          cmake-build-args: "-DCMAKE_CXX_STANDARD=17 -DABSL_PROPAGATE_CXX_STD=ON -DABSL_ENABLE_INSTALL=ON -DBUILD_TESTING=off -DCMAKE_POSITION_INDEPENDENT_CODE=ON"
          abseil-version: "20240722.0"
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install .
      - run: pip install pytest
      - run: pytest

